# Generated by Django 4.2 on 2023-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_comment',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
