# Generated by Django 4.2 on 2023-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_no_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_read_comment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='not_read_comment_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
