# Generated by Django 4.2 on 2023-01-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_not_read_comment_id_user_not_read_comment_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='not_read_comment_id',
        ),
    ]
