# Generated by Django 4.2 on 2023-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddle', '0004_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seen_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
